# Generated by Django 4.2.13 on 2025-09-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='published_at',
        ),
    ]
