# Generated by Django 4.2.13 on 2025-09-24 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def create_default_lesson(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    Lesson = apps.get_model('lessons', 'Lesson')

    # Example: python-data-science course me ek lesson create karna
    try:
        course = Course.objects.get(slug='python-data-science')
        Lesson.objects.create(
            course=course,
            title='Introduction',
            content_file=None,
            video=None,
        )
    except Course.DoesNotExist:
        pass
    
class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_description_courseinteraction'),
        ('lessons', '0003_remove_lesson_created_at_remove_lesson_updated_at_and_more'),
    ]
    operations = [
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='resources',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'slug'], name='lessons_les_course__e0c606_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order_index'], name='lessons_les_course__633840_idx'),
        ),
    ]
