# Generated by Django 4.2.13 on 2025-09-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_description_courseinteraction'),
        ('lessons', '0004_lesson_created_at_lesson_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_in_lessons_app', to='courses.course'),
        ),
    ]
