# Generated by Django 4.2.13 on 2025-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/content/'),
        ),
    ]
