# Generated by Django 5.2.5 on 2025-09-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_remove_lesson_content_lesson_content_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='lesson_filename',
            field=models.CharField(default='default-course', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='lesson',
        ),
    ]
