# Generated by Django 5.2.5 on 2025-09-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lessonprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='course_slug',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson_filename',
            field=models.CharField(max_length=200),
        ),
    ]
