# Generated by Django 4.2.13 on 2025-09-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_lessonprogress_course_slug_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lesson',
            name='lessons_les_course__e0c606_idx',
        ),
        migrations.RemoveIndex(
            model_name='lesson',
            name='lessons_les_course__633840_idx',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order_index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
