# Generated by Django 4.2.13 on 2025-10-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_lesson_course_alter_course_options_and_more'),
        ('lessons', '0009_remove_lesson_lessons_les_course__e0c606_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
    ]
