# Generated by Django 4.2.13 on 2025-10-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_lesson_content_path_lesson_content_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed',
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='lessons.lesson'),
        ),
    ]
