# Generated by Django 4.2.13 on 2025-09-21 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examprogress',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress_records_for_exam', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='exams.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='updated_at',
        ),
    ]
