# Generated by Django 4.2.13 on 2025-09-21 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentprofile_bio_studentprofile_completed_lessons_and_more'),
        ('courses', '0006_course_teacher_exam_date_alter_course_description_and_more'),
        ('exams', '0002_alter_examprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examfeedback',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='examfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='examoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='exam',
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='pass_percentage',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='user',
        ),
        migrations.AddField(
            model_name='exam',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='examprogress',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examprogress',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examprogress',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_from_external', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exam'),
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='ExamFeedback',
        ),
        migrations.DeleteModel(
            name='ExamOption',
        ),
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
    ]
