# Generated by Django 5.2.5 on 2025-09-22 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='courses.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
                ('progress', models.JSONField(default=dict)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_records', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_progress', to='courses.exam')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('progress', models.JSONField(default=dict)),
                ('exam_scores', models.JSONField(default=dict)),
                ('assignments_submitted', models.JSONField(default=dict)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('achievements', models.JSONField(default=list)),
                ('completed_lessons', models.ManyToManyField(blank=True, to='courses.lesson')),
                ('enrolled_courses', models.ManyToManyField(blank=True, related_name='students', to='courses.course')),
                ('pending_assignments', models.ManyToManyField(related_name='pending_students', to='courses.courseassignment')),
            ],
        ),
    ]
