# Generated by Django 4.2.13 on 2025-09-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examprogress_unique_together_and_more'),
        ('courses', '0004_alter_lesson_course_exam'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='marks_obtained',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofile'),
        ),
        migrations.CreateModel(
            name='ExamProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_progress', to='exams.exam')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress_records', to='students.studentprofile')),
            ],
        ),
    ]
