# Generated by Django 4.2.13 on 2025-09-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseassignment_enrollment_alter_lesson_options_and_more'),
        ('students', '0002_remove_assignmentsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='courses.lesson'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='courses.course'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pending_assignments',
            field=models.ManyToManyField(related_name='pending_students', to='courses.courseassignment'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='courses.exam'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='students.studentprofile'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_records', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_records', to='students.studentprofile'),
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_progress', to='courses.exam'),
        ),
    ]
