# Generated by Django 4.2.13 on 2025-09-22 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_assignments', to='courses.exam'),
        ),
    ]
