# Generated by Django 4.2.13 on 2025-10-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_lesson_content_path_lesson_content_text_and_more'),
        ('students', '0003_alter_assignmentsubmission_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='lessons.lesson'),
        ),
    ]
