# Generated by Django 4.2.13 on 2025-10-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_delete_lesson'),
        ('students', '0004_alter_studentprofile_completed_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrolled_courses',
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_assignments', to='courses.exam'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='pending_assignments',
            field=models.ManyToManyField(blank=True, related_name='pending_students', to='courses.courseassignment'),
        ),
    ]
