# Generated by Django 5.2.5 on 2025-11-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_delete_lesson'),
        ('exams', '0001_initial'),
        ('students', '0006_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-date_enrolled']},
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_assignments', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_progress', to='exams.exam'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
    ]
