# Generated by Django 4.2.13 on 2025-10-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
        ('lessons', '0009_remove_lesson_lessons_les_course__e0c606_idx_and_more'),
        ('courses', '0005_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='courseinteraction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to='teachers.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='courseinteraction',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='lessons.lesson'),
        ),
    ]
