# Generated by Django 4.2.13 on 2025-10-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_alter_lessonprogress_options_and_more'),
        ('courses', '0006_remove_lesson_course_alter_course_options_and_more'),
        ('students', '0004_alter_studentprofile_completed_lessons'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
