# Generated by Django 5.2.5 on 2025-09-22 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Score obtained in this lesson', max_digits=5)),
                ('completed', models.BooleanField(default=False, help_text='Whether the lesson has been completed')),
                ('lesson', models.ForeignKey(help_text='The lesson associated with this result', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'Lesson Result',
                'verbose_name_plural': 'Lesson Results',
                'ordering': ['-id'],
            },
        ),
    ]
