# Generated by Django 4.2.13 on 2025-10-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_lesson_content_path_lesson_content_text_and_more'),
        ('students', '0004_alter_studentprofile_completed_lessons'),
        ('progress', '0003_lessonprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name': 'Lesson Progress', 'verbose_name_plural': 'Lesson Progress Records'},
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='lessons.lesson'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('student', 'lesson')},
        ),
    ]
